adding request timeouts
interfax/interfax-python pull request #8
Opened 2017-07-11 20:44 UTC by danielknell

this adds an optional third param to the clients constructor which can be used to set the request timeout.

2017-07-12 10:19 UTC, cbetta requested changes

2017-07-12 10:19 UTC, cbetta commented on README.rst
> +The client takes a timeout parameter, this is passed directly to the underlying
Can we specify if this is in seconds, milliseconds, or other?

2017-07-14 14:50 UTC, danielknell commented on README.rst
> +The client takes a timeout parameter, this is passed directly to the underlying
hows the new wording look?

2017-07-14 15:08 UTC, cbetta approved these changes

2017-07-14 15:08 UTC, cbetta commented
Ship it!

2017-07-14 16:02 UTC, merged